name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'
    
    # - name: Install Dependencies
    #   run: npm install
      
    # - name: Build Application
    #   run: npm run build
      
    - name: Deploy to Server
      run: |
        # Replace the following commands with your deployment steps
        
        # Copy the built files to the server using SCP
        scp -r ./ssh -i "backend-deployment.pem" ubuntu@ec2-65-0-102-109.ap-south-1.compute.amazonaws.com/Testing-deployment
        
        # SSH into the server
        ec2-65-0-102-109.ap-south-1.compute.amazonaws.com '
          cd /path/to/destination
          # Install dependencies
          npm install
          # Restart the application
          npm run restart
        '
